import streamlit as st
from datetime import datetime

def render_safety_page(router):
    """
    Renders the Safety & Disclaimers page.
    This page is static and does not require authentication.
    """
    
    st.set_page_config(page_title="Safety & Disclaimers - Diagnoze AI", layout="wide")

    st.title("Safety, Disclaimers, and Limitations")
    st.warning("**Important:** This application is not a substitute for professional medical advice, diagnosis, or treatment.")

    if st.button("Home"):
        router.redirect(*router.build("dashboard"))

    sections = [
        ("Educational Purpose Only", "Diagnoze AI is an educational tool designed to provide information about medical conditions and symptoms. The information provided is generated by an AI model based on medical literature and datasets. It is intended to help users understand health topics but should **never** be used for self-diagnosis or to make treatment decisions."),
        ("Not a Diagnostic Tool", "**This is not a diagnostic tool.** The AI's suggestions are based on statistical patterns and probabilities, not a clinical evaluation. An accurate medical diagnosis can only be made by a qualified healthcare professional who can consider your complete medical history, conduct a physical examination, and order necessary tests."),
        ("Limitation of Liability", "The creators of Diagnoze AI, its developers, and its affiliates are not liable for any actions taken by users based on the information provided by this application. By using Diagnoze AI, you agree that you are doing so at your own risk. We do not guarantee the accuracy, completeness, or timeliness of the information provided."),
        ("When to Seek Professional Medical Help", "If you are experiencing a medical emergency, call your local emergency number immediately (e.g., 911 in the U.S.). Seek immediate medical attention if you have symptoms such as:", [
            "Difficulty breathing or shortness of breath",
            "Chest pain or pressure",
            "Sudden numbness, weakness, or confusion",
            "Severe headache or abdominal pain",
            "Loss of consciousness",
            "Uncontrolled bleeding"
        ]),
        ("Data Privacy Statement", "We are committed to protecting your privacy. The data you provide, such as symptoms and chat history, is used to personalize your experience and improve the underlying AI model. All personal identifying information is handled with strict confidentiality. Please refer to our full **Privacy Policy** for more details on data collection, usage, and protection."),
        ("User Acknowledgment", "By using the chat feature or browsing the educational library, you acknowledge that you have read, understood, and agreed to the terms outlined in this disclaimer. You accept that Diagnoze AI is an educational tool and not a replacement for professional medical care.")
    ]

    for title, content, *extra in sections:
        st.header(title)
        st.write(content)
        if extra:
            st.markdown("\n".join([f"- {item}" for item in extra[0]]))

    ack = st.checkbox("I have read and understood the safety disclaimers.")
    if ack:
        st.success("Thank you for your acknowledgment.")
    else:
        st.warning("Please acknowledge the disclaimers to proceed with using all features of the application.")

    st.markdown("---")
    last_updated = datetime(2026, 2, 20)
    st.markdown(f"<p style='text-align: right; color: grey;'><i>Last updated: {last_updated.strftime('%B %d, %Y')}</i></p>", unsafe_allow_html=True)

