BEGIN TRANSACTION;
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (1,'panic disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (2,'vaginitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (3,'problem during pregnancy',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (4,'acute pancreatitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (5,'asthma',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (6,'infectious gastroenteritis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (7,'acute sinusitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (8,'cornea infection',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (9,'marijuana abuse',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (10,'bursitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (11,'actinic keratosis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (12,'chronic obstructive pulmonary disease (copd)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (13,'spondylosis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (14,'injury to the arm',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (15,'complex regional pain syndrome',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (16,'injury to the trunk',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (17,'vulvodynia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (18,'concussion',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (19,'hypoglycemia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (20,'hiatal hernia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (21,'allergy',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (22,'acute bronchospasm',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (23,'degenerative disc disease',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (24,'pain after an operation',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (25,'injury to the leg',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (26,'gout',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (27,'otitis media',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (28,'acute kidney injury',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (29,'threatened pregnancy',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (30,'gum disease',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (31,'gastrointestinal hemorrhage',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (32,'anxiety',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (33,'conjunctivitis due to allergy',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (34,'drug reaction',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (35,'macular degeneration',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (36,'pneumonia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (37,'vaginal cyst',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (38,'carpal tunnel syndrome',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (39,'nose disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (40,'dental caries',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (41,'hypertensive heart disease',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (42,'seasonal allergies (hay fever)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (43,'fungal infection of the hair',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (44,'rectal disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (45,'stye',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (46,'heart attack',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (47,'obstructive sleep apnea (osa)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (48,'psoriasis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (49,'arthritis of the hip',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (50,'sickle cell crisis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (51,'otitis externa (swimmer''s ear)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (52,'acute bronchiolitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (53,'pyogenic skin infection',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (54,'noninfectious gastroenteritis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (55,'benign prostatic hyperplasia (bph)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (56,'spinal stenosis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (57,'acute bronchitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (58,'croup',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (59,'idiopathic excessive menstruation',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (60,'ear drum damage',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (61,'temporary or benign blood in urine',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (62,'common cold',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (63,'depression',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (64,'idiopathic irregular menstrual cycle',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (65,'schizophrenia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (66,'sepsis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (67,'cholecystitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (68,'cystitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (69,'hemorrhoids',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (70,'contact dermatitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (71,'sinus bradycardia',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (72,'pelvic inflammatory disease',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (73,'liver disease',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (74,'chronic constipation',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (75,'skin polyp',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (76,'brachial neuritis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (77,'esophagitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (78,'diverticulitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (79,'sprain or strain',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (80,'idiopathic painful menstruation',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (81,'eustachian tube dysfunction (ear disorder)',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (82,'appendicitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (83,'hyperemesis gravidarum',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (84,'urinary tract infection',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (85,'peripheral nerve disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (86,'sebaceous cyst',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (87,'spontaneous abortion',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (88,'gallstone',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (89,'multiple sclerosis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (90,'angina',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (91,'skin pigmentation disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (92,'personality disorder',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (93,'strep throat',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (94,'developmental disability',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (95,'chronic back pain',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (96,'heart failure',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (97,'conjunctivitis',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (98,'herniated disk',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (99,'diaper rash',NULL,NULL);
INSERT INTO "disease" ("disease_id","disease_name","category","severity_level") VALUES (100,'eczema',NULL,NULL);
COMMIT;
