BEGIN TRANSACTION;
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (1,'anxiety and nervousness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (2,'depression',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (3,'shortness of breath',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (4,'depressive or psychotic symptoms',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (5,'sharp chest pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (6,'dizziness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (7,'insomnia',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (8,'abnormal involuntary movements',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (9,'chest tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (10,'palpitations',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (11,'irregular heartbeat',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (12,'breathing fast',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (13,'hoarse voice',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (14,'sore throat',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (15,'difficulty speaking',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (16,'cough',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (17,'nasal congestion',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (18,'throat swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (19,'diminished hearing',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (20,'difficulty in swallowing',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (21,'skin swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (22,'retention of urine',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (23,'leg pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (24,'hip pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (25,'suprapubic pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (26,'blood in stool',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (27,'lack of growth',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (28,'symptoms of the scrotum and testes',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (29,'swelling of scrotum',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (30,'pain in testicles',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (31,'pus draining from ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (32,'jaundice',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (33,'white discharge from eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (34,'irritable infant',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (35,'abusing alcohol',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (36,'fainting',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (37,'hostile behavior',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (38,'drug abuse',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (39,'sharp abdominal pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (40,'feeling ill',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (41,'vomiting',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (42,'headache',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (43,'nausea',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (44,'diarrhea',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (45,'vaginal itching',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (46,'painful urination',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (47,'involuntary urination',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (48,'pain during intercourse',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (49,'frequent urination',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (50,'lower abdominal pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (51,'vaginal discharge',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (52,'blood in urine',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (53,'hot flashes',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (54,'intermenstrual bleeding',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (55,'hand or finger pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (56,'wrist pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (57,'hand or finger swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (58,'arm pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (59,'wrist swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (60,'arm stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (61,'arm swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (62,'hand or finger stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (63,'lip swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (64,'toothache',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (65,'abnormal appearing skin',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (66,'skin lesion',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (67,'acne or pimples',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (68,'facial pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (69,'mouth ulcer',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (70,'skin growth',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (71,'diminished vision',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (72,'double vision',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (73,'symptoms of eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (74,'pain in eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (75,'abnormal movement of eyelid',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (76,'foreign body sensation in eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (77,'irregular appearing scalp',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (78,'back pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (79,'neck pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (80,'low back pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (81,'pain of the anus',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (82,'pain during pregnancy',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (83,'pelvic pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (84,'impotence',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (85,'vomiting blood',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (86,'regurgitation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (87,'burning abdominal pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (88,'restlessness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (89,'wheezing',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (90,'peripheral edema',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (91,'neck mass',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (92,'ear pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (93,'jaw swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (94,'mouth dryness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (95,'neck swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (96,'knee pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (97,'foot or toe pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (98,'ankle pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (99,'bones are painful',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (100,'elbow pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (101,'knee swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (102,'skin moles',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (103,'weight gain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (104,'problems with movement',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (105,'knee stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (106,'leg swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (107,'foot or toe swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (108,'heartburn',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (109,'infant feeding problem',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (110,'vaginal pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (111,'vaginal redness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (112,'weakness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (113,'decreased heart rate',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (114,'increased heart rate',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (115,'ringing in ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (116,'plugged feeling in ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (117,'itchy ear(s)',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (118,'frontal headache',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (119,'fluid in ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (120,'spots or clouds in vision',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (121,'eye redness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (122,'lacrimation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (123,'itchiness of eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (124,'blindness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (125,'eye burns or stings',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (126,'decreased appetite',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (127,'excessive anger',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (128,'loss of sensation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (129,'focal weakness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (130,'symptoms of the face',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (131,'disturbance of memory',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (132,'paresthesia',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (133,'side pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (134,'fever',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (135,'shoulder pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (136,'shoulder stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (137,'ache all over',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (138,'lower body pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (139,'problems during pregnancy',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (140,'spotting or bleeding during pregnancy',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (141,'cramps and spasms',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (142,'upper abdominal pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (143,'stomach bloating',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (144,'changes in stool appearance',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (145,'unusual color or odor to urine',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (146,'kidney mass',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (147,'symptoms of prostate',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (148,'difficulty breathing',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (149,'rib pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (150,'joint pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (151,'hand or finger lump or mass',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (152,'chills',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (153,'groin pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (154,'fatigue',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (155,'regurgitation.1',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (156,'symptoms of the kidneys',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (157,'melena',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (158,'coughing up sputum',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (159,'seizures',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (160,'delusions or hallucinations',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (161,'excessive urination at night',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (162,'bleeding from eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (163,'rectal bleeding',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (164,'constipation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (165,'temper problems',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (166,'coryza',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (167,'hemoptysis',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (168,'allergic reaction',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (169,'congestion in chest',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (170,'sleepiness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (171,'apnea',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (172,'abnormal breathing sounds',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (173,'blood clots during menstrual periods',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (174,'pulling at ears',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (175,'gum pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (176,'redness in ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (177,'fluid retention',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (178,'flu-like syndrome',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (179,'sinus congestion',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (180,'painful sinuses',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (181,'fears and phobias',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (182,'recent pregnancy',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (183,'uterine contractions',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (184,'burning chest pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (185,'back cramps or spasms',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (186,'back mass or lump',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (187,'nosebleed',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (188,'long menstrual periods',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (189,'heavy menstrual flow',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (190,'unpredictable menstruation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (191,'painful menstruation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (192,'infertility',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (193,'frequent menstruation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (194,'sweating',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (195,'mass on eyelid',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (196,'swollen eye',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (197,'eyelid swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (198,'eyelid lesion or rash',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (199,'symptoms of bladder',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (200,'irregular appearing nails',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (201,'itching of skin',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (202,'hurts to breath',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (203,'skin dryness, peeling, scaliness, or roughness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (204,'skin irritation',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (205,'itchy scalp',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (206,'warts',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (207,'skin rash',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (208,'mass or swelling around the anus',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (209,'ankle swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (210,'elbow swelling',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (211,'bleeding from ear',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (212,'hand or finger weakness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (213,'low self-esteem',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (214,'itching of the anus',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (215,'swollen or red tonsils',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (216,'hip stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (217,'mouth pain',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (218,'arm weakness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (219,'obsessions and compulsions',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (220,'antisocial behavior',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (221,'sneezing',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (222,'leg weakness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (223,'hysterical behavior',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (224,'arm lump or mass',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (225,'bleeding gums',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (226,'pain in gums',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (227,'diaper rash',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (228,'hesitancy',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (229,'back stiffness or tightness',NULL);
INSERT INTO "symptoms" ("symptom_id","symptom_name","category") VALUES (230,'low urine output',NULL);
COMMIT;
